version: '3.1'

services:
  springboot:
    build: .
    restart: always
    container_name: simian-service
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: simian-mongo
    hostname: simian-mongo
    volumes:
      - $HOME/data/simian-mongo-data:/data/db
      - $HOME/data/simian-mongo-bkp:/data/bkp
    restart: always